college/college/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    # path('',include('account.urls')),
    path('', include('home.urls')),
    path('',include('Admin.urls')),
    path('', include("account.urls")),
    path('',include("notifications.urls")),
    path('',include("wishlist.urls")),

]

college/home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns =[
    path('',views.front),
    path('user_dashboard/',views.user_dashboard),
    path('faq/', views.faq),
    path('filter/', views.filter),
    path('search/', views.search, name="search"),
    path('college_dashboard/', views.college_dashboard),
    path('user_colleges/',views.user_colleges),
    path('user_college_details/<int:id>',views.user_college_details),
    path('user_wishlist/<int:id>', views.user_wishlist),
    path('my_colleges/', views.show_cart_items),
    path('remove_item/<int:cart_id>', views.remove_cart_item),

]

college/notifications/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'notifications'
urlpatterns = [
    path('is_read/<int:pk>/', views.seenNotification, name='is_read'),
    path('add_notifications/', views.add_notifications),
]

college/templates/admin-header.html
{% load notification %}
	<!-- header start -->
	<header class="ttr-header">
		<div class="ttr-header-wrapper">
			<!--sidebar menu toggler start -->
			<div class="ttr-toggle-sidebar ttr-material-button">
				<i class="ti-close ttr-open-icon"></i>
				<i class="ti-menu ttr-close-icon"></i>
			</div>
			<!--sidebar menu toggler end -->
			<!--logo start -->
			<div class="ttr-logo-box">
				<div>
					<a href="index.html" class="ttr-logo">
						<img class="ttr-logo-mobile" alt="" src="../static/images/CF1_logo.png" width="30" height="30">
						<img class="ttr-logo-desktop" alt="" src="../static/images/CF1_logo.png" width="100" height="20">
					</a>
				</div>
			</div>
			<!--logo end -->
			<div class="ttr-header-menu">
				<!-- header left menu start -->
				<ul class="ttr-header-navigation">

					<li>
						<a href="/logout">Log Out</a>
					</li>
				</ul>
				<!-- header left menu end -->
			</div>
			<div class="ttr-header-right ttr-with-seperator">
				<!-- header right menu start -->
				<ul class="ttr-header-navigation">

					<li>
						<a href="#" class="ttr-material-button ttr-submenu-toggle"><i class="fa fa-bell"></i>
						{% if request.user|notification_count %}
                                            <span class="cart-count">{{ request.user|notification_count}}</span>
                                        {% else %}
                                        <span class="cart-count">0</span>
                                        {% endif %}</a>
						<div class="ttr-header-submenu noti-menu">
							<div class="ttr-notify-header">

								<span class="ttr-notify-text">Admin Notifications</span>
							</div>
							<div class="noti-box-list">
								<ul>
									{% for notification in request.user|notifications %}
										<li>
											<span class="notification-icon dashbg-yellow">
												<i class="fa fa-bullhorn"></i>
											</span>
											<span class="notification-text">
												<a href="">{{ notification.message }}</a>
											</span>
											<div style="float:right;">
											<span class="notifications-time">
												<a href="{% url 'notifications:is_read' notification.pk %}" class="fa fa-close" id="hello"></a>
											</span>
												</div>

										</li>
									{% endfor %}
								</ul>
							</div>
						</div>
					</li>
					<li>
						<a href="" class="ttr-material-button ttr-submenu-toggle"><span class="ttr-user-avatar">
							{% for notification in request.user|admin_profiles %}
							<img alt="" src="/{{notification.profile_picture}}" width="32" height="32"></span></a>
                                        {% endfor %}
						<div class="ttr-header-submenu">
							<ul>
								<li><a href="/user_profile">My profile</a></li>
								<li><a href="list-view-calendar.html">Activity</a></li>
								<li><a href="mailbox.html">Messages</a></li>
								<li><a href="../login.html">Logout</a></li>
							</ul>
						</div>
					</li>

				</ul>
				<!-- header right menu end -->
			</div>
			<!--header search panel start -->
			<div class="ttr-search-bar">
				<form class="ttr-search-form">
					<div class="ttr-search-input-wrapper">
						<input type="text" name="qq" placeholder="search something..." class="ttr-search-input">
						<button type="submit" name="search" class="ttr-search-submit"><i class="ti-arrow-right"></i></button>
					</div>
					<span class="ttr-search-close ttr-search-toggle">
						<i class="ti-close"></i>
					</span>
				</form>
			</div>
			<!--header search panel end -->
		</div>
	</header>
	<!-- header end -->
	<!-- Left sidebar menu start -->
	<div class="ttr-sidebar">
		<div class="ttr-sidebar-wrapper content-scroll">
			<!-- side menu logo start -->
			<div class="ttr-sidebar-logo">
				<a href="#"><img alt="" src="../static/images/CF1_logo.png" width="50" height="10"style="margin-left:60px;"></a>
				<!-- <div class="ttr-sidebar-pin-button" title="Pin/Unpin Menu">
					<i class="material-icons ttr-fixed-icon">gps_fixed</i>
					<i class="material-icons ttr-not-fixed-icon">gps_not_fixed</i>
				</div> -->
				<div class="ttr-sidebar-toggle-button">
					<i class="ti-arrow-left"></i>
				</div>
			</div>
			<!-- side menu logo end -->
			<!-- sidebar menu start -->
			<nav class="ttr-sidebar-navi">
				<ul>
					<li>
						<a href="/admin_dashboard" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-home"></i></span>
		                	<span class="ttr-label">Dashborad</span>
		                </a>
		            </li>
					<li>
						<a href="/add_college" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-book"></i></span>
		                	<span class="ttr-label"> Add Colleges</span>
		                </a>
		            </li>
					<li>
						<a href="/show_colleges" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-bookmark-alt"></i></span>
		                	<span class="ttr-label">show colleges</span>
		                </a>
		            </li>
					<li>
						<a href="/add_notifications" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-bookmark-alt"></i></span>
		                	<span class="ttr-label">Add notifications</span>
		                </a>
		            </li>



					<li>
						<a href="/admin_profile" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-user"></i></span>
		                	<span class="ttr-label">My Profile</span>
		                </a>
		            </li>
					<li>
						<a href="/users" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-user"></i></span>
		                	<span class="ttr-label">Users</span>
		                </a>
		            </li>
					<li>
						<a href="/admins" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-user"></i></span>
		                	<span class="ttr-label">Admins</span>

		                </a>
		            </li>
					<li>
						<a href="/user_admission" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-user"></i></span>
		                	<span class="ttr-label">User Admissions</span>
		                </a>
		            </li>
		            <li class="ttr-seperate"></li>
				</ul>
				<!-- sidebar menu end -->
			</nav>
			<!-- sidebar menu end -->
		</div>
	</div>
	<!-- Left sidebar menu end -->

college/templates/admin-layout.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap %}
<html lang="en">

<head>
	{% block style %}
    {{section.style}}
    {% endblock style%}

	<!-- META ============================================= -->
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<meta name="robots" content="" />

	<!-- DESCRIPTION -->


	<!-- FAVICONS ICON ============================================= -->
	<link rel="icon" href="../error-404.html" type="image/x-icon" />
	<link rel="shortcut icon" type="image/x-icon" href="../static/images/CF1_logo.png" />

	<!-- PAGE TITLE HERE ============================================= -->
	<title>College Finder</title>

	<!-- MOBILE SPECIFIC ============================================= -->
	<meta name="viewport" content="width=device-width, initial-scale=1">

<!--	<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">-->
<!--	<link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">-->

	<!--[if lt IE 9]>
	<script src="../static/assets_user/js/html5shiv.min.js"></script>
	<script src="../static/assets_user/js/respond.min.js"></script>
	<![endif]-->
<!--	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">-->
<!-- &lt;!&ndash; JavaScript Bundle with Popper &ndash;&gt;-->
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

	<!-- All PLUGINS CSS ============================================= -->
	<link rel="stylesheet" type="text/css" href="../static/assets_user/css/assets.css">
	<link rel="stylesheet" type="text/css" href="../static/assets_user/vendors/calendar/fullcalendar.css">

	<!-- TYPOGRAPHY ============================================= -->
	<link rel="stylesheet" type="text/css" href="../static/assets_user/css/typography.css">

	<!-- SHORTCODES ============================================= -->
	<link rel="stylesheet" type="text/css" href="../static/assets_user/css/shortcodes/shortcodes.css">

	<!-- STYLESHEETS ============================================= -->
	<link rel="stylesheet" type="text/css" href="../static/assets_user/css/style.css">
	<link rel="stylesheet" type="text/css" href="../static/assets_user/css/dashboard.css">
	<link class="skin" rel="stylesheet" type="text/css" href="../static/assets_user/css/color/color-1.css">

<!--     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"-->
<!--           integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"-->
<!--           crossorigin="anonymous">-->
<!--	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

</head>
<body class="ttr-opened-sidebar ttr-pinned-sidebar">

 {% include 'admin-header.html' %}
    {% block main_content %}
    {% endblock main_content %}
    {% include 'admin-footer.html' %}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
<!--<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="-->
<!--        crossorigin="anonymous"></script>-->

<!--<script src="{% static 'js/owl.carousel.min.js' %}"></script>-->
<!--<script src="{% static 'js/all.min.js' %}"></script>-->
<!--<script src="{% static 'js/myscript.js' %}"></script>-->


<!-- <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>-->
<!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>-->
<!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->

<!-- External JavaScripts -->
<script src="../static/assets_user/js/jquery.min.js"></script>
<script src="../static/assets_user/vendors/bootstrap/js/popper.min.js"></script>
<script src="../static/assets_user/vendors/bootstrap/js/bootstrap.min.js"></script>
<script src="../static/assets_user/vendors/bootstrap-select/bootstrap-select.min.js"></script>
<script src="../static/assets_user/vendors/bootstrap-touchspin/jquery.bootstrap-touchspin.js"></script>
<script src="../static/assets_user/vendors/magnific-popup/magnific-popup.js"></script>
<script src="../static/assets_user/vendors/counter/waypoints-min.js"></script>
<script src="../static/assets_user/vendors/counter/counterup.min.js"></script>
<script src="../static/assets_user/vendors/imagesloaded/imagesloaded.js"></script>
<script src="../static/assets_user/vendors/masonry/masonry.js"></script>
<script src="../static/assets_user/vendors/masonry/filter.js"></script>
<script src="../static/assets_user/vendors/owl-carousel/owl.carousel.js"></script>
<script src='../static/assets_user/vendors/scroll/scrollbar.min.js'></script>
<script src="../static/assets_user/js/functions.js"></script>
<script src="../static/assets_user/vendors/chart/chart.min.js"></script>
<script src="../static/assets_user/js/admin.js"></script>
<script src='../static/assets_user/vendors/calendar/moment.min.js'></script>
<script src='../static/assets_user/vendors/calendar/fullcalendar.js'></script>
<script src='../static/assets_user/vendors/switcher/switcher.js'></script>
<script>
  $(document).ready(function() {

    $('#calendar').fullCalendar({
      header: {
        left: 'prev,next today',
        center: 'title',
        right: 'month,agendaWeek,agendaDay,listWeek'
      },
      defaultDate: '2019-03-12',
      navLinks: true, // can click day/week names to navigate views

      weekNumbers: true,
      weekNumbersWithinDays: true,
      weekNumberCalculation: 'ISO',

      editable: true,
      eventLimit: true, // allow "more" link when too many events
      events: [
        {
          title: 'All Day Event',
          start: '2019-03-01'
        },
        {
          title: 'Long Event',
          start: '2019-03-07',
          end: '2019-03-10'
        },
        {
          id: 999,
          title: 'Repeating Event',
          start: '2019-03-09T16:00:00'
        },
        {
          id: 999,
          title: 'Repeating Event',
          start: '2019-03-16T16:00:00'
        },
        {
          title: 'Conference',
          start: '2019-03-11',
          end: '2019-03-13'
        },
        {
          title: 'Meeting',
          start: '2019-03-12T10:30:00',
          end: '2019-03-12T12:30:00'
        },
        {
          title: 'Lunch',
          start: '2019-03-12T12:00:00'
        },
        {
          title: 'Meeting',
          start: '2019-03-12T14:30:00'
        },
        {
          title: 'Happy Hour',
          start: '2019-03-12T17:30:00'
        },
        {
          title: 'Dinner',
          start: '2019-03-12T20:00:00'
        },
        {
          title: 'Birthday Party',
          start: '2019-03-13T07:00:00'
        },
        {
          title: 'Click for Google',
          url: 'http://google.com/',
          start: '2019-03-28'
        }
      ]
    });

  });

</script>
<script>
	$(document).ready(function() {
    $('.switcher-btn-bx').hide();
});
</script>
{% block script %}
    {{section.script}}
    {% endblock script %}
</body>
</html>

college/templates/messages.html
{% for msg in messages %}
{% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
<div class="alert alert-success alert-dismissible fade show" id = "msg" role="alert">
    {{msg}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
{% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
<div class="alert alert-danger alert-dismissible fade show" id="msg1" role="alert">
    {{msg}}
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}

{% endfor %}

<script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 1000)
  </script>

college/templates/user_footer.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

college/templates/user_header.html
{% load notification %}

	<!-- header start -->
	<header class="ttr-header">
		<div class="ttr-header-wrapper">
			<!--sidebar menu toggler start -->
			<div class="ttr-toggle-sidebar ttr-material-button">
				<i class="ti-close ttr-open-icon"></i>
				<i class="ti-menu ttr-close-icon"></i>
			</div>
			<!--sidebar menu toggler end -->
			<!--logo start -->
			<div class="ttr-logo-box">
				<div>
					<a href="/" class="ttr-logo">
<!--						<img class="ttr-logo-mobile" alt="" src="../static/images/CF1_logo.png" width="20" height="20">-->
						<img class="ttr-logo-desktop" alt="" src="../static/images/CF1_logo.png" width="75" height="20">
					</a>
				</div>
			</div>
			<!--logo end -->
			<div class="ttr-header-menu">
				<!-- header left menu start -->
				<ul class="ttr-header-navigation">


				</ul>
				<!-- header left menu end -->
			</div>
			<div class="ttr-header-right ttr-with-seperator">
				<!-- header right menu start -->
				<ul class="ttr-header-navigation">

					<li>
						<a href="/my_colleges" class="ttr-material-button"><i class="fa fa-heart">
											{% if request.user|notification_counts %}
                                            <span class="cart-count">{{ request.user|notification_counts}}</span>
                                        {% else %}
                                        <span class="cart-count">0</span>
                                        {% endif %}

						</i></a>
					</li>
					<li>
						<a href="/get_notification" class="ttr-material-button ttr-submenu-toggle"><i class="fa fa-bell">

                                        {% if request.user|notification_count %}
                                            <span class="cart-count">{{ request.user|notification_count}}</span>
                                        {% else %}
                                        <span class="cart-count">0</span>
                                        {% endif %}

						</i>

						</a>

						<div class="ttr-header-submenu noti-menu">
							<div class="ttr-notify-header">
<!--								<span class="ttr-notify-text-top">9 New</span>-->

								<span class="ttr-notify-text">User Notifications</span>
							</div>

							<div class="noti-box-list">
								<ul>
<!--									<li>-->
<!--										<span class="notifications-icon dashbg-gray">-->
<!--											<i class="fa fa-check"></i>-->
<!--										</span>-->
<!--										<span class="notifications-text">-->
<!--											<span>Sneha Jogi</span> sent you a message.-->
<!--										</span>-->
<!--										<span class="notifications-time">-->
<!--											<a href="#" class="fa fa-close"></a>-->
<!--											<span> 02:14</span>-->
<!--										</span>-->
<!--									</li>-->
									{% for notification in request.user|notifications %}
										<li>
											<span class="notification-icon dashbg-yellow">
												<i class="fa fa-bullhorn"></i>
											</span>
											<span class="notification-text">
												<a href="">{{ notification.message }}</a>
											</span>
											<div style="float:right;">
											<span class="notifications-time">
												<a href="{% url 'notifications:is_read' notification.pk %}" class="fa fa-close" id="hello"></a>
											</span>
												</div>

										</li>
									{% endfor %}


<!--									{% for i in notifications %}-->
<!--									<li>-->
<!--										<span class="notifications-icon dashbg-red">-->
<!--											<i class="fa fa-bullhorn"></i>-->
<!--										</span>-->
<!--										<span class="notifications-text">-->
<!--											<span>{{i.news}}</span> sent you a message.-->
<!--										</span>-->
<!--										<span class="notifications-time">-->
<!--											<a href="#" class="fa fa-close"></a>-->
<!--											<span> {{i.created_date}}</span>-->
<!--										</span>-->
<!--									</li>-->
<!--									{% endfor %}-->
<!--									<li>-->
<!--										<span class="notifications-icon dashbg-green">-->
<!--											<i class="fa fa-comments-o"></i>-->
<!--										</span>-->
<!--										<span class="notifications-text">-->
<!--											<a href="#">Sneha Jogi</a> sent you a message.-->
<!--										</span>-->
<!--										<span class="notifications-time">-->
<!--											<a href="#" class="fa fa-close"></a>-->
<!--											<span> 14 July</span>-->
<!--										</span>-->
<!--									</li>-->
<!--									<li>-->
<!--										<span class="notifications-icon dashbg-primary">-->
<!--											<i class="fa fa-file-word-o"></i>-->
<!--										</span>-->
<!--										<span class="notifications-text">-->
<!--											<span>Sneha Jogi</span> sent you a message.-->
<!--										</span>-->
<!--										<span class="notifications-time">-->
<!--											<a href="#" class="fa fa-close"></a>-->
<!--											<span> 15 Min</span>-->
<!--										</span>-->
<!--									</li>-->
								</ul>

							</div>

						</div>
					</li>
					<li>
						<a href="" class="ttr-material-button ttr-submenu-toggle"><span class="ttr-user-avatar">
							{% for notification in request.user|user_profiles %}
							<img alt="" src="/{{notification.profile_picture}}" width="32" height="32"></span></a>
                                        {% endfor %}

						<div class="ttr-header-submenu">
							<ul>
								<li><a href="/user_profile">My profile</a></li>
								<li><a href="list-view-calendar.html">Activity</a></li>
								<li><a href="mailbox.html">Messages</a></li>
								<li><a href="/logout">Logout</a></li>
							</ul>
						</div>
					</li>


				</ul>
				<!-- header right menu end -->
			</div>
			<!--header search panel start -->
			<div class="ttr-search-bar">
				<form class="ttr-search-form">
					<div class="ttr-search-input-wrapper">
						<input type="text" name="qq" placeholder="search something..." class="ttr-search-input">
						<button type="submit" name="search" class="ttr-search-submit"><i class="ti-arrow-right"></i></button>
					</div>
					<span class="ttr-search-close ttr-search-toggle">
						<i class="ti-close"></i>
					</span>
				</form>
			</div>
			<!--header search panel end -->
		</div>
	</header>
	<!-- header end -->
	<!-- Left sidebar menu start -->
	<div class="ttr-sidebar">
		<div class="ttr-sidebar-wrapper content-scroll">
			<!-- side menu logo start -->
			<div class="ttr-sidebar-logo">
				<a href="#"><img alt="" src="../static/images/CF1_logo.png" width="50" height="10"style="margin-left:60px;"></a>
				<!-- <div class="ttr-sidebar-pin-button" title="Pin/Unpin Menu">
					<i class="material-icons ttr-fixed-icon">gps_fixed</i>
					<i class="material-icons ttr-not-fixed-icon">gps_not_fixed</i>
				</div> -->
				<div class="ttr-sidebar-toggle-button">
					<i class="ti-arrow-left"></i>
				</div>
			</div>
			<!-- side menu logo end -->
			<!-- sidebar menu start -->
			<nav class="ttr-sidebar-navi">
				<ul>
					<li>
						<a href="/user_dashboard" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-home"></i></span>
		                	<span class="ttr-label">Dashborad</span>
		                </a>
		            </li>
					<li>
						<a href="/user_colleges" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-book"></i></span>
		                	<span class="ttr-label">Colleges</span>
		                </a>
		            </li>
					<li>
						<a href="/my_colleges" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-bookmark-alt"></i></span>
		                	<span class="ttr-label">Bookmarks</span>
		                </a>
		            </li>


					<li>
						<a href="/user_profile" class="ttr-material-button">
							<span class="ttr-icon"><i class="ti-user"></i></span>
		                	<span class="ttr-label">My Profile</span>

		                </a>

		            </li>
		            <li class="ttr-seperate"></li>
				</ul>
				<!-- sidebar menu end -->
			</nav>
			<!-- sidebar menu end -->
		</div>
	</div>
	<!-- Left sidebar menu end -->